%bcond_without weak_deps

%global __os_install_post %(echo '%{__os_install_post}' | sed -e 's!/usr/lib[^[:space:]]*/brp-python-bytecompile[[:space:]].*$!!g')
%global __provides_exclude_from ^/opt/ros/noetic/.*$
%global __requires_exclude_from ^/opt/ros/noetic/.*$

Name:           ros-noetic-libfranka
Version:        0.8.0
Release:        4%{?dist}%{?release_suffix}
Summary:        ROS libfranka package

License:        Apache 2.0
URL:            https://frankaemika.github.io
Source0:        %{name}-%{version}.tar.gz

Requires:       poco-devel
Requires:       ros-noetic-catkin
BuildRequires:  cmake
BuildRequires:  eigen3-devel
BuildRequires:  poco-devel
Provides:       %{name}-devel = %{version}-%{release}
Provides:       %{name}-doc = %{version}-%{release}
Provides:       %{name}-runtime = %{version}-%{release}

%description
libfranka is a C++ library for Franka Emika research robots

%prep
%autosetup

%build
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
mkdir -p obj-%{_target_platform} && cd obj-%{_target_platform}
%cmake3 \
    -UINCLUDE_INSTALL_DIR \
    -ULIB_INSTALL_DIR \
    -USYSCONF_INSTALL_DIR \
    -USHARE_INSTALL_PREFIX \
    -ULIB_SUFFIX \
    -DCMAKE_INSTALL_LIBDIR="lib" \
    -DCMAKE_INSTALL_PREFIX="/opt/ros/noetic" \
    -DCMAKE_PREFIX_PATH="/opt/ros/noetic" \
    -DBUILD_DOCUMENTATION=OFF \
    -DBUILD_EXAMPLES=ON \
    -DBUILD_TESTS=ON \
    -DSETUPTOOLS_DEB_LAYOUT=OFF \
    -DCATKIN_BUILD_BINARY_PACKAGE="1" \
    ..

%make_build

%install
# In case we're installing to a non-standard location, look for a setup.sh
# in the install tree that was dropped by catkin, and source it.  It will
# set things like CMAKE_PREFIX_PATH, PKG_CONFIG_PATH, and PYTHONPATH.
if [ -f "/opt/ros/noetic/setup.sh" ]; then . "/opt/ros/noetic/setup.sh"; fi
%make_install -C obj-%{_target_platform}

%files
/opt/ros/noetic

%changelog
* Wed Jul 15 2020 Franka Emika GmbH <support@franka.de> - 0.8.0-4
- Autogenerated by Bloom

* Thu Jul 02 2020 Franka Emika GmbH <support@franka.de> - 0.8.0-3
- Autogenerated by Bloom

* Tue Jun 30 2020 Franka Emika GmbH <support@franka.de> - 0.8.0-2
- Autogenerated by Bloom

