services:
  libfranka_project:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        USER_UID: ${USER_UID}
        USER_GID: ${USER_GID}
    container_name: libfranka
    network_mode: "host"
    shm_size: 512m
    privileged: true
    command: /bin/bash
    tty: true
    stdin_open: true
    volumes:
      - ../:/workspaces
    cap_add:
      - SYS_NICE
    ulimits:
      rtprio: 99
      rttime: -1
      memlock: 8428281856
      